#:kivy 1.9.0

<timerWidget>:
    labeldatetime: labeldatetimeval
    buttoncount: buttoncountval

    #Labeldatetime
    Label:
        id: labeldatetimeval
        font_size: 50
        center_x: (root.width/2)
        top: root.top
        text: 'time'
    #buttoncount
    Button:
        id: buttoncountval
        font_size: 50
        center_x: (root.width/2)
        size: 140,70
        top: root.top-180
        text: 'Click!'
